### ISSUE TITLE
fails on vagrant install

### ISSUE THREAD

**Issue by danmayer** [noahgibbs/madscience_gem#4]
newly install madscience bombs out on Vagrant

rbenv sudo madscience construct
Recipe: vagrant::mac_os_x
- dmg_package[Vagrant] action install
  - remote_file[/var/chef/cache/Vagrant.dmg - Vagrant] action create
    # 
    
    Error executing action `create` on resource 'remote_file[/var/chef/cache/Vagrant.dmg - Vagrant]'
    ## Chef::Exceptions::ChecksumMismatch
    
    Checksum on resource (a94a16) does not match checksum on content (eaeb3a)
    ## Resource Declaration:
    # In /Users/danmayer/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/madscience-0.0.20/cookbooks/dmg/providers/package.rb
    
    39:       remote_file "#{dmg_file} - #{@dmgpkg.name}" do
    40:         path dmg_file
    41:         source new_resource.source
    42:         checksum new_resource.checksum if new_resource.checksum
    43:       end
    44:     end
    ## Compiled Resource:
    # Declared in /Users/danmayer/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/madscience-0.0.20/cookbooks/dmg/providers/package.rb:39:in `block in class_from_file'
    
    remote_file("/var/chef/cache/Vagrant.dmg - Vagrant") do
      provider Chef::Provider::RemoteFile
      action "create"
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      path "/var/chef/cache/Vagrant.dmg"
      backup 5
      atomic_update true
      source ["https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.1.dmg"]
      use_etag true
      use_last_modified true
      declared_type :remote_file
      cookbook_name :vagrant
      checksum "a94a16b9ed5f63460f64110738067aea029238f8d826c8dd90c5c34615a5be1e"
    end

**Comment by noahgibbs** [comment]
Interesting! I'll check the cookbook today and see if they've changed the package or something. I assume you've already tried running again to make sure it didn't die mid-download or something.

**Comment by danmayer** [comment]
yeah I uninstalled previously installed vagrant versions in case there was some conflict.. then ran again

**Comment by noahgibbs** [comment]
Found an odd SSL error, but only on older Ruby versions. Looks like you're not getting that.

I've uninstalled Vagrant and reinstalled without this error. I'll look through the Vagrant cookbook and see if there might be something else going on with the checksum. We should definitely be installing the same Vagrant version, presumably with the same checksum (if any) handed to Chef.

**Comment by noahgibbs** [comment]
Huh. Now that's interesting. You're providing what looks like a valid checksum ("a94a16b9ed5f63460f64110738067aea029238f8d826c8dd90c5c34615a5be1e"), which would normally mean, "oh, the cookbook is out of date."

But nope, the cookbook is getting the checksum from a URL during the Chef run (https://dl.bintray.com/mitchellh/vagrant/1.7.1_SHA256SUMS?direct). Oddly, I don't see the specific checksum you're using in that list.

Can you try again and see if maybe the URL was briefly out of date or something?

**Comment by danmayer** [comment]
weird still failing... So here is a more complete dump in case it helps. Thanks for taking a look into this, something odd is happening.

```
ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
[~/projects] rbenv sudo madscience construct
Password:
WARN: Unresolved specs during Gem::Specification.reset:
      mime-types (~> 2.0)
      ffi (~> 1.5, ~> 1.9)
      rake (>= 10.0.0, ~> 10.1)
      net-ssh (< 3.0, >= 2.2.2, >= 2.6.5, >= 2.8.0, ~> 2.6)
      highline (>= 1.6.9, ~> 1.6)
      diff-lcs (>= 1.2.4, ~> 1.2)
      hashie (~> 2.0)
      uuidtools (~> 2.1)
      rack (>= 0)
      pry (~> 0.9)
      thor (~> 0.15)
      i18n (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Installing apt (2.6.1)
Installing chef_handler (1.1.6)
Installing dmg (2.2.2)
Installing windows (1.36.6)
Installing vagrant (0.2.2)
Installing yum (3.5.3)
Installing virtualbox (0.7.2)
fatal: Not a git repository (or any of the parent directories): .git
Starting Chef Client, version 12.0.3
Compiling Cookbooks...
Converging 14 resources
Recipe: vagrant::mac_os_x
  * dmg_package[Vagrant] action install
    * remote_file[/var/chef/cache/Vagrant.dmg - Vagrant] action create

      ================================================================================
      Error executing action `create` on resource 'remote_file[/var/chef/cache/Vagrant.dmg - Vagrant]'
      ================================================================================

      Chef::Exceptions::ChecksumMismatch
      ----------------------------------
      Checksum on resource (a94a16) does not match checksum on content (eaeb3a)

      Resource Declaration:
      ---------------------
      # In /Users/danmayer/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/madscience-0.0.20/cookbooks/dmg/providers/package.rb

       39:       remote_file "#{dmg_file} - #{@dmgpkg.name}" do
       40:         path dmg_file
       41:         source new_resource.source
       42:         checksum new_resource.checksum if new_resource.checksum
       43:       end
       44:     end

      Compiled Resource:
      ------------------
      # Declared in /Users/danmayer/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/madscience-0.0.20/cookbooks/dmg/providers/package.rb:39:in `block in class_from_file'

      remote_file("/var/chef/cache/Vagrant.dmg - Vagrant") do
        provider Chef::Provider::RemoteFile
        action "create"
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        path "/var/chef/cache/Vagrant.dmg"
        backup 5
        atomic_update true
        source ["https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.1.dmg"]
        use_etag true
        use_last_modified true
        declared_type :remote_file
        cookbook_name :vagrant
        checksum "a94a16b9ed5f63460f64110738067aea029238f8d826c8dd90c5c34615a5be1e"
      end


    ================================================================================
    Error executing action `install` on resource 'dmg_package[Vagrant]'
    ================================================================================

    Chef::Exceptions::ChecksumMismatch
    ----------------------------------
    remote_file[/var/chef/cache/Vagrant.dmg - Vagrant] (/Users/danmayer/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/madscience-0.0.20/cookbooks/dmg/providers/package.rb line 39) had an error: Chef::Exceptions::ChecksumMismatch: Checksum on resource (a94a16) does not match checksum on content (eaeb3a)

    Resource Declaration:
    ---------------------
    # In /Users/danmayer/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/madscience-0.0.20/cookbooks/vagrant/recipes/mac_os_x.rb

      1: dmg_package "Vagrant" do
      2:   source node['vagrant']['url']
      3:   checksum node['vagrant']['checksum']
      4:   type "pkg"
      5:   package_id "com.vagrant.vagrant"
      6:   action :install
      7: end

    Compiled Resource:
    ------------------
    # Declared in /Users/danmayer/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/madscience-0.0.20/cookbooks/vagrant/recipes/mac_os_x.rb:1:in `from_file'

    dmg_package("Vagrant") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :dmg_package
      cookbook_name :vagrant
      recipe_name "mac_os_x"
      source "https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.1.dmg"
      checksum "a94a16b9ed5f63460f64110738067aea029238f8d826c8dd90c5c34615a5be1e"
      type "pkg"
      package_id "com.vagrant.vagrant"
      app "Vagrant"
      destination "/Applications"
    end


Running handlers:
[2015-03-27T11:05:53-06:00] ERROR: Running exception handlers
Running handlers complete
[2015-03-27T11:05:53-06:00] ERROR: Exception handlers complete
[2015-03-27T11:05:53-06:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 63.225626 seconds
[2015-03-27T11:05:53-06:00] ERROR: dmg_package[Vagrant] (vagrant::mac_os_x line 1) had an error: Chef::Exceptions::ChecksumMismatch: remote_file[/var/chef/cache/Vagrant.dmg - Vagrant] (/Users/danmayer/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/madscience-0.0.20/cookbooks/dmg/providers/package.rb line 39) had an error: Chef::Exceptions::ChecksumMismatch: Checksum on resource (a94a16) does not match checksum on content (eaeb3a)
[2015-03-27T11:05:53-06:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
/Users/danmayer/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/madscience-0.0.20/bin/madscience:73:in `block in do_local_setup': Failed during chef run! (RuntimeError)
    from /Users/danmayer/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/madscience-0.0.20/bin/madscience:42:in `in_madscience_dir'
    from /Users/danmayer/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/madscience-0.0.20/bin/madscience:70:in `do_local_setup'
    from /Users/danmayer/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/madscience-0.0.20/bin/madscience:131:in `<top (required)>'
    from /Users/danmayer/.rbenv/versions/2.1.5/bin/madscience:23:in `load'
    from /Users/danmayer/.rbenv/versions/2.1.5/bin/madscience:23:in `<main>'
```

**Comment by noahgibbs** [comment]
Do me a favor: get to a command line and run this command (sorry, had to add "curl"):

   curl https://dl.bintray.com/mitchellh/vagrant/1.7.1_SHA256SUMS?direct

Presumably your checksum, the one starting with "a94", comes from there.

Post the output here. For reference, here's what I get:

   eaeb3ad6624ccaeaefa6fc7a77a2f5d9640ef9385c5eeebdb90602d5f2011176  vagrant_1.7.1.dmg
   abab1db382be4c5d6b1e5aad96fb0909a559c3e500c5b2eb3f0c9178de7d1ac5  vagrant_1.7.1.msi
   4396385d3493931634c5f12e464a991f75f36c93783d392c60100112ec3d406d  vagrant_1.7.1_i686.deb
   6e405a855c4426b04f568f62740f04025c548b2f722a4b3faee94b0b2ce19bc0  vagrant_1.7.1_i686.rpm
   6615b95fcd8044e2f5e1849ec1004df5e05e390812558ec2c4b3dcec541b92da  vagrant_1.7.1_x86_64.deb
   b66be4b8f7921f59b00c186344c8501f97a26e172e94c3add7298b5147bcab27  vagrant_1.7.1_x86_64.rpm

**Comment by danmayer** [comment]
I use zsch so just in case I ran in bash, but got the same error.

output

```
[~/projects] curl "https://dl.bintray.com/mitchellh/vagrant/1.7.1_SHA256SUMS?direct"
eaeb3ad6624ccaeaefa6fc7a77a2f5d9640ef9385c5eeebdb90602d5f2011176  vagrant_1.7.1.dmg
abab1db382be4c5d6b1e5aad96fb0909a559c3e500c5b2eb3f0c9178de7d1ac5  vagrant_1.7.1.msi
4396385d3493931634c5f12e464a991f75f36c93783d392c60100112ec3d406d  vagrant_1.7.1_i686.deb
6e405a855c4426b04f568f62740f04025c548b2f722a4b3faee94b0b2ce19bc0  vagrant_1.7.1_i686.rpm
6615b95fcd8044e2f5e1849ec1004df5e05e390812558ec2c4b3dcec541b92da  vagrant_1.7.1_x86_64.deb
b66be4b8f7921f59b00c186344c8501f97a26e172e94c3add7298b5147bcab27  vagrant_1.7.1_x86_64.rpm
```

**Comment by danmayer** [comment]
based on the error output wouldn't I expect to find the Vagrant file here so I could manually check the checksum, that file isn't there (unless Chef is cleaning it up)

ls /var/chef/cache/
Emacs-24.3-universal-10.6.8.dmg chef-client-running.pid         iTerm2.zip
XQuartz.dmg                     chef-stacktrace.out             propane.zip
bash_it                         homebrew                        remote_file

**Comment by noahgibbs** [comment]
I believe Chef cleans it up.

You're seeing the same checksums I am in the curl output, and you're clearly also using the DMG package (Mac OS). I assume you haven't edited files anywhere that would clearly set a Checksum in an attribute...

I'll look through the code again and see if I can see any other way for that checksum to be set.

**Comment by noahgibbs** [comment]
(Also, I tested the same thing locally, before asking you to run the curl command, and it worked fine for me. Which is why I keep asking you questions about your setup.)

**Comment by noahgibbs** [comment]
With the default setup, it should be downloading that file from "https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.1.dmg". So if you wanted to check the file and see if the checksum was reasonable, that would be the file.

But then, you _should_ presumably be using the checksum "eaeb3ad6624ccaeaefa6fc7a77a2f5d9640ef9385c5eeebdb90602d5f2011176", as you see in the Curl output, instead of the checksum "a94a16b9ed5f63460f64110738067aea029238f8d826c8dd90c5c34615a5be1e", which is what I'm seeing in your Chef output :-(

**Comment by danmayer** [comment]
yeah odd. I will download manually and check the checksum and see what I get something odd must be wrong with my setup. I am going to grab lunch and then will take a look.

**Comment by danmayer** [comment]
so this doesn't seem to match at all but I must be doing something wrong:

```
shasum ~/Downloads/vagrant_1.7.1.dmg
13a4c428aee94d5a9fe77ff92699f19507795dee  /Users/danmayer/Downloads/vagrant_1.7.1.dmg
```

I did find something interesting the weird 'a94a16b9ed5f63460f64110738067aea029238f8d826c8dd90c5c34615a5be1e' that I keep getting exists here:
https://github.com/caskroom/homebrew-versions/blob/master/Casks/vagrant165.rb

I  tried updating brew and making sure I didn't have vagrant installed via brew. Still go the same error. My thought is something somewhere must be cached incorrectly on my system.

**Comment by noahgibbs** [comment]
Huh. The really interesting thing about that checksum there is that it's for Vagrant 1.6.5, _not_ Vagrant 1.7.1. Which might be what you'd get if Vagrant was going off the standard attributes rather than correctly querying for the version being used.

**Comment by noahgibbs** [comment]
It would be possible to go into the MadScience directory and set an attribute for that checksum -- or to, perhaps more easily, just cut out the place where we specify the checksum in the (very small) mac_os_x Chef recipe.

In both of those cases you'd need to modify ugly stuff in your installed gem directory, though.

Right! Time for manual install instructions :-/ I'll add a TODO.

Otherwise, no clue what's going on. Vagrant 1.6.5 _is_ the default version in the Vagrant cookbook, which is being overridden by MadScience to install 1.7.1. But that doesn't give me any good clues about why it isn't being overridden in this case...

**Comment by noahgibbs** [comment]
I've pushed a change to GitHub (but not Rubygems!) to override the Vagrant checksum manually based on my run of curl.

Can I ask you to clone the repo, then type the following commands?
- bundle install
- sudo rm -rf cookbooks/*
- librarian-chef install
- rvmsudo bundle exec bin/madscience setup

This should use the new change that overrides the checksum. If it works for you, I'll push it to Rubygems.

(It works for me locally.)

**Comment by danmayer** [comment]
Awesome, success! Thanks so much for digging into this!

```
   - create new file /Users/danmayer/.deploy_credentials/authorized_keys
    - change owner from '' to 'danmayer'

Running handlers:
Running handlers complete
Chef Client finished, 23/24 resources updated in 234.020948 seconds
```

**Comment by noahgibbs** [comment]
Excellent! I've pushed version 0.0.21 to Rubygems to fix this.
